    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nexus02
      namespace: nexus02
    spec:
      replicas: 1
      selector:
        matchLabels:
            app: nexus-server02
      template:
        metadata:
          labels:
            app: nexus-server02
        spec:
          containers:
            - name: nexus02
              image: sonatype/nexus3:latest
              resources:
                limits:
                  memory: "4Gi"
                  cpu: "1000m"
                requests:
                  memory: "2Gi"
                  cpu: "500m"
              ports:
                - containerPort: 8081
              volumeMounts:
                - name: nexus-data
                  mountPath: /nexus-data
          volumes:
            - name: nexus-data
              emptyDir: {}

